version: '3.8'
services:
  server:
    build: './server'
    ports:
      - 9001:80
    container_name: terminal-server

  client:
    build: './client'
    ports:
      - 9000:3000
    container_name: terminal-client
    environment:
      - REACT_APP_HUB_URL=http://host.docker.internal:9001
    depends_on:
      - server
